### ISSUE TITLE
no text of the solution appears

### ISSUE THREAD

**Issue by ILohs** [Dobherrmann/MMM-Losung#1]
Thanks for creating this project! I have used it in the MM config within the modules and do not get a result on the screen either online or with access to the texts from the local file. Does it work for you?

**Comment by Dobherrmann** [comment]
hey thanks for the information. on my MM it's working. I use the magic mirror in a docker container.
https://hub.docker.com/r/karsten13/magicmirror 

How do you use the the magic mirror. I know there are some issues container from with basti limbach. (Different node version)

**Comment by Dobherrmann** [comment]
@ILohs: I updated the package file if you are still interested you can test my update I hope the module will work for you now

**Comment by ILohs** [comment]
I installed again and get this Error-Message:
node_module_version 93. This version of Node.js requires
node_module_version 89. Please try re-compiling or re-installing.
npm rebuild nor npm install help at this step.

Before I updated my PI4 with this described steps:
https://officialrajdeepsingh.dev/install-node-js-and-npm-latest-version-on-raspberry-pi-4/
https://nodejs.org/en/download/

Thx for your support anyway!

**Comment by Dobherrmann** [comment]
Hey ILohs,
sorry for the long waiting time. But I had the chance to test the module during christmas on a second raspi. The issue is that I used modules which are working with different node modules version. You can fix it as it is described here: https://forum.magicmirror.builders/topic/15715/mmm-pir-sensor-error/2

On top I removed the local file reading because I think it easyer to fetch the Losung directly from the web. I have to make a new release and change the readme :)

**Comment by ILohs** [comment]
Thx for your help! It works like described.

cd ~/MagicMirror
npm install electron-rebuild
cd modules/MMM-Losung
~/MagicMirror/node_modules/.bin/electron-rebuild
